language: java
jdk:
- openjdk8
dist:
  trust
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - devcodx87@gmail.com
services:
- mysql
script:
- mvn verify
#Test unitario y de integracion en perfil DEV, con cobertura
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
# SONARCLOUD PRODUCTOS
#- mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=devcodxec -Dsonar.login=$MEETUP